spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
  flyway:
    url: jdbc:mysql://avnadmin:AVNS_La_DidM8gznKaCox7Ye@blisgo-blisgo.aivencloud.com:20548/defaultdb?ssl-mode=REQUIRED
    user: avnadmin
    password: AVNS_La_DidM8gznKaCox7Ye
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_La_DidM8gznKaCox7Ye@blisgo-blisgo.aivencloud.com:20548/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_La_DidM8gznKaCox7Ye
    hikari:
      maximum-pool-size: 20
  devtools:
    livereload:
      enabled: true