spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    url: jdbc:mysql://root:V1VVs2Kek6skaijyVvdQ@containers-us-west-80.railway.app:7646/railway?&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false
    user: root
    password: V1VVs2Kek6skaijyVvdQ

  datasource:
    url: jdbc:mysql://root:V1VVs2Kek6skaijyVvdQ@containers-us-west-80.railway.app:7646/railway?&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false
    username: root
    password: V1VVs2Kek6skaijyVvdQ

  devtools:
    add-properties: false